# Go-CQHTTP的默认配置文件, 没必要最好不要动
# 以三个`{}`包裹的为模板项, 请不要修改

account: # 账号相关
  password: "{{{account.password}}}" # 密码为空时使用扫码登录
  encrypt: false # 是否开启密码加密
  status: 0 # 在线状态 请参考 https://docs.go-cqhttp.org/guide/config.html#在线状态

  relogin: # 重连设置
    delay: 3 # 首次重连延迟, 单位秒
    interval: 3 # 重连间隔
    max-times: 0 # 最大重连次数, 0为无限制

  # 是否使用服务器下发的新地址进行重连
  # 注意, 此设置可能导致在海外服务器上连接情况更差
  use-sso-address: true

  # prettier-ignore
  uin: {{{account.uin}}} # QQ账号

heartbeat:
  # 心跳频率, 单位秒
  # -1 为关闭心跳
  interval: 5

message:
  # 上报数据类型
  # 可选: string,array
  post-format: array

  # 是否忽略无效的CQ码, 如果为假将原样发送
  ignore-invalid-cqcode: false

  # 是否强制分片发送消息
  # 分片发送将会带来更快的速度
  # 但是兼容性会有些问题
  force-fragment: false

  # 是否将url分片发送
  fix-url: false

  # 下载图片等请求的网络代理
  proxy-rewrite: ""

  # 是否上报自身消息
  report-self-message: false

  # 移除服务端的Reply附带的At
  remove-reply-at: false

  # 为Reply附加更多信息
  extra-reply-data: false

  # 跳过 Mime 扫描, 忽略错误数据
  skip-mime-scan: false

output:
  # 日志等级: trace,debug,info,warn,error
  log-level: warn

  # 日志时效 单位天. 超过这个时间之前的日志将会被自动删除. 设置为 0 表示永久保留.
  log-aging: 15

  # 是否在每次启动时强制创建全新的文件储存日志. 为 false 的情况下将会在上次启动时创建的日志文件续写
  log-force-new: true

  # 是否启用 DEBUG
  debug: false # 开启调试模式

  # 输出日志颜色设置, 会影响前台日志输出, 请勿修改
  log-colorful: false

# 默认中间件锚点
default-middlewares: &default # 访问密钥, 强烈推荐在公网的服务器设置
  access-token: ""

  # 事件过滤器文件目录
  filter: ""

  # API限速设置
  # 该设置为全局生效
  rate-limit:
    enabled: false # 是否启用限速
    frequency: 1 # 令牌回复频率, 单位秒
    bucket: 1 # 令牌桶大小

database: # 数据库相关设置
  leveldb:
    # 是否启用内置leveldb数据库
    # 启用将会增加10-20MB的内存占用和一定的磁盘空间
    # 关闭将无法使用 撤回 回复 get_msg 等上下文相关功能
    enable: true

  # 媒体文件缓存， 删除此项则使用缓存文件(旧版行为)
  # 若需要将所有账号的缓存设置为同一份，可尝试将路径设置为同一个。但可能会带来写冲突问题，请谨慎设置
  cache:
    image: data/image.db
    video: data/video.db

servers:
  - ws-reverse:
      universal: "{{{server_address}}}"
      reconnect-interval: 3000
      middlewares:
        <<: *default
        access-token: "{{{access_token}}}"
